services:
  - type: web
    name: diet-recommendation-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python src/train_models.py && python src/evaluate.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
